// POST /api/exec/workspace-init
// Creates the workspace directory and seeds it with AGENTS.md + CLAUDE.md.
// When existingRepo is provided the repo is cloned and a feature branch is
// created + published before AGENTS.md / CLAUDE.md are written.

import { NextRequest, NextResponse } from 'next/server';
import { runInContainer } from '@/services/dockerExec';

interface InitBody {
  runId: string;
  title: string;
  spec: string;
  /** Git URL of an existing repo to clone instead of creating a blank workspace */
  existingRepo?: string;
  /** Feature branch name to create and push; required when existingRepo is set */
  featureBranch?: string;
}

const WORKSPACE_ROOT = '/home/coder/workspace';

function escapeShellHeredoc(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\$/g, '\\$').replace(/`/g, '\\`');
}

/** Reject strings containing characters that break single-quoted shell arguments */
function isSafeForShellSingleQuote(s: string): boolean {
  return !s.includes("'");
}

function isValidGitUrl(url: string): boolean {
  if (!isSafeForShellSingleQuote(url)) return false;
  return (
    /^https:\/\/[a-zA-Z0-9._\-@:/]+(?:\.git)?$/.test(url) ||
    /^git@[a-zA-Z0-9._\-]+:[a-zA-Z0-9._\-/]+(?:\.git)?$/.test(url)
  );
}

function isValidBranchName(branch: string): boolean {
  if (!isSafeForShellSingleQuote(branch)) return false;
  // No shell specials, no consecutive dots, no leading slash
  return /^[a-zA-Z0-9][a-zA-Z0-9._\-/]{0,99}$/.test(branch) && !branch.includes('..');
}

export async function POST(req: NextRequest) {
  let body: InitBody;
  try {
    body = (await req.json()) as InitBody;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { runId, title, spec, existingRepo, featureBranch } = body;

  if (!runId || !/^[a-zA-Z0-9_\-]+$/.test(runId)) {
    return NextResponse.json({ error: 'invalid runId' }, { status: 400 });
  }
  if (!title || typeof title !== 'string') {
    return NextResponse.json({ error: 'title is required' }, { status: 400 });
  }
  if (existingRepo !== undefined) {
    if (!isValidGitUrl(existingRepo)) {
      return NextResponse.json({ error: 'invalid existingRepo URL' }, { status: 400 });
    }
    if (!featureBranch || !isValidBranchName(featureBranch)) {
      return NextResponse.json({ error: 'invalid or missing featureBranch' }, { status: 400 });
    }
  }

  const workspaceDir = `${WORKSPACE_ROOT}/${runId}`;
  const safeTitle   = escapeShellHeredoc(title.slice(0, 200));
  const safeSpec    = escapeShellHeredoc((spec ?? '').slice(0, 4000));
  const date        = new Date().toISOString().split('T')[0];

  const agentsContent = `# Project: ${safeTitle}\\n\\nGenerated by Open Pilot on ${date}.\\n\\n## Purpose\\n\\n${safeSpec}\\n\\n## Agent Working Rules\\n\\n- Write complete, production-ready code — no placeholders or TODOs.\\n- Run \`npm install\` / \`pip install\` before building when adding new dependencies.\\n- Run the build/test suite and fix all errors before marking a task done.\\n- Prefer editing existing files over creating new ones.\\n- Keep this file (AGENTS.md) updated as architecture, build commands, or conventions evolve.\\n\\n## Architecture\\n\\n<!-- The agent will fill this in as the project is built. -->\\n\\n## Build & Run\\n\\n<!-- The agent will fill this in. -->\\n\\n## Testing\\n\\n<!-- The agent will fill this in. -->\\n`;
  const claudeContent = `@AGENTS.md\\n`;

  let cmd: string;

  if (existingRepo && featureBranch) {
    // Clone the existing repo, create + publish the feature branch, then seed context files
    cmd = [
      `git clone '${existingRepo}' '${workspaceDir}'`,
      `git -C '${workspaceDir}' checkout -b '${featureBranch}'`,
      // Attempt to publish; capture result without failing the whole command
      `(git -C '${workspaceDir}' push -u origin '${featureBranch}' 2>&1 && echo '___PUSH_OK___' || echo '___PUSH_FAIL___')`,
      `printf '%b' '${agentsContent}' > '${workspaceDir}/AGENTS.md'`,
      `printf '%b' '${claudeContent}' > '${workspaceDir}/CLAUDE.md'`,
    ].join(' && ');
  } else {
    cmd = [
      `mkdir -p '${workspaceDir}'`,
      `printf '%b' '${agentsContent}' > '${workspaceDir}/AGENTS.md'`,
      `printf '%b' '${claudeContent}' > '${workspaceDir}/CLAUDE.md'`,
    ].join(' && ');
  }

  try {
    const result = await runInContainer(cmd, '/home/coder', existingRepo ? 120_000 : 15_000);
    if (result.exitCode !== 0) {
      return NextResponse.json(
        { error: `workspace init failed: ${result.output.slice(0, 300)}` },
        { status: 500 },
      );
    }
    const branchPushed = existingRepo ? result.output.includes('___PUSH_OK___') : undefined;
    return NextResponse.json({ ok: true, ...(existingRepo ? { branchPushed } : {}) });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : String(err) },
      { status: 500 },
    );
  }
}
