// POST /api/exec/workspace-init
// Creates the workspace directory and seeds it with AGENTS.md + CLAUDE.md
// so every future AI agent that works in this repo has the right context.

import { NextRequest, NextResponse } from 'next/server';
import { runInContainer } from '@/services/dockerExec';

interface InitBody {
  runId: string;
  title: string;
  spec: string;
}

const WORKSPACE_ROOT = '/home/coder/workspace';

function escapeShellHeredoc(s: string): string {
  // Escape characters that would break a heredoc delimiter-guarded block
  return s.replace(/\\/g, '\\\\').replace(/\$/g, '\\$').replace(/`/g, '\\`');
}

export async function POST(req: NextRequest) {
  let body: InitBody;
  try {
    body = (await req.json()) as InitBody;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { runId, title, spec } = body;

  if (!runId || !/^[a-zA-Z0-9_\-]+$/.test(runId)) {
    return NextResponse.json({ error: 'invalid runId' }, { status: 400 });
  }
  if (!title || typeof title !== 'string') {
    return NextResponse.json({ error: 'title is required' }, { status: 400 });
  }

  const workspaceDir = `${WORKSPACE_ROOT}/${runId}`;
  const safeTitle   = escapeShellHeredoc(title.slice(0, 200));
  const safeSpec    = escapeShellHeredoc((spec ?? '').slice(0, 4000));
  const date        = new Date().toISOString().split('T')[0];

  // Use printf to write files so no shell-interpretation of the content occurs
  const agentsContent = `# Project: ${safeTitle}\\n\\nGenerated by Open Pilot on ${date}.\\n\\n## Purpose\\n\\n${safeSpec}\\n\\n## Agent Working Rules\\n\\n- Write complete, production-ready code — no placeholders or TODOs.\\n- Run \`npm install\` / \`pip install\` before building when adding new dependencies.\\n- Run the build/test suite and fix all errors before marking a task done.\\n- Prefer editing existing files over creating new ones.\\n- Keep this file (AGENTS.md) updated as architecture, build commands, or conventions evolve.\\n\\n## Architecture\\n\\n<!-- The agent will fill this in as the project is built. -->\\n\\n## Build & Run\\n\\n<!-- The agent will fill this in. -->\\n\\n## Testing\\n\\n<!-- The agent will fill this in. -->\\n`;

  const claudeContent = `@AGENTS.md\\n`;

  const cmd = [
    `mkdir -p '${workspaceDir}'`,
    `printf '%b' '${agentsContent}' > '${workspaceDir}/AGENTS.md'`,
    `printf '%b' '${claudeContent}' > '${workspaceDir}/CLAUDE.md'`,
  ].join(' && ');

  try {
    const result = await runInContainer(cmd, '/home/coder', 15_000);
    if (result.exitCode !== 0) {
      return NextResponse.json(
        { error: `workspace init failed: ${result.output.slice(0, 300)}` },
        { status: 500 },
      );
    }
    return NextResponse.json({ ok: true });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : String(err) },
      { status: 500 },
    );
  }
}
